# Generated by Django 5.0.7 on 2024-07-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tage', models.CharField(max_length=10)),
                ('location', models.TextField()),
                ('area', models.IntegerField()),
                ('property_type', models.CharField(max_length=15)),
                ('bed', models.IntegerField()),
                ('carparking', models.IntegerField()),
            ],
        ),
    ]
