# Generated by Django 5.0.7 on 2024-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('alternative_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('facilities', models.TextField()),
                ('property_details', models.TextField()),
                ('property_area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('furnishing', models.CharField(blank=True, max_length=50)),
                ('bedroom', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('living_room', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('car_parking', models.IntegerField()),
            ],
        ),
    ]
